{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e631b171",
   "metadata": {},
   "outputs": [],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.support.ui import Select\n",
    "from datetime import date, timedelta\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver import ActionChains\n",
    "from selenium.common.exceptions import NoSuchElementException\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from collections import Counter\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from bs4 import BeautifulSoup\n",
    "from datetime import datetime\n",
    "\n",
    "import time\n",
    "import logging\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "7a996627",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_weather_data_for_dates7(start_year, start_month, start_day, end_year, end_month, end_day, browser):\n",
    "\n",
    "    weather_data = {}\n",
    "    current_date = datetime(start_year, start_month, start_day)\n",
    "    end_date = datetime(end_year, end_month, end_day)\n",
    "    problematic_urls = []\n",
    "    while current_date <= end_date:\n",
    "        try:\n",
    "            year, month, day = current_date.year, current_date.month, current_date.day\n",
    "            if not browser.current_window_handle: # Check if browser is still open\n",
    "                browser.quit()\n",
    "                time.sleep(15)\n",
    "                browser = webdriver.Firefox()\n",
    "                browser.maximize_window()\n",
    "            date_data = get_weather_data4(year, month, day, browser)\n",
    "            weather_data[current_date.strftime(\"%Y-%m-%d\")] = date_data\n",
    "        except Exception as e:\n",
    "            max_retries = 1 # usually on - 5 tries \n",
    "            retries = 0\n",
    "            while retries < max_retries:\n",
    "                try:\n",
    "                    browser.quit()\n",
    "                    time.sleep(15)\n",
    "                    browser = webdriver.Firefox()\n",
    "                    browser.maximize_window()\n",
    "                    date_data = get_weather_data4(year, month, day, browser)\n",
    "                    weather_data[current_date.strftime(\"%Y-%m-%d\")] = date_data\n",
    "                    break\n",
    "                except Exception as e:\n",
    "                    retries += 1\n",
    "                    time.sleep(30)\n",
    "                    logging.error(\"An error occurred while getting data for date %s: %s\", current_date, e)\n",
    "                except SessionNotFoundException:\n",
    "                    browser.quit()\n",
    "                    time.sleep(15)\n",
    "                    browser = webdriver.Firefox()\n",
    "                    browser.maximize_window()\n",
    "                    date_data = get_weather_data4(year, month, day, browser)\n",
    "                    weather_data[current_date.strftime(\"%Y-%m-%d\")] = date_data\n",
    "            if retries == max_retries:\n",
    "                current_url = browser.current_url\n",
    "                browser.quit()\n",
    "                logging.error(\"Maximum number of retries reached for date %s\", current_date)\n",
    "                problematic_urls.append((current_date.strftime(\"%Y-%m-%d\"), current_url))\n",
    "        current_date += timedelta(days=1)\n",
    "    browser.quit()\n",
    "    return weather_data, problematic_urls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "8c6f2fa5",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_weather_data4( year, month, day, browser):\n",
    "    try:\n",
    "        # Open browser and navigate to the website\n",
    "        #browser = webdriver.Chrome()\n",
    "        wait = WebDriverWait(browser, 20)\n",
    "        browser.get('https://www.wunderground.com/history') #https://www.wunderground.com/history/daily/il/haifa/LLHA\n",
    "        wait.until(EC.presence_of_element_located((By.ID, 'yearSelection')))\n",
    "        wait.until(EC.presence_of_element_located((By.ID, 'historySearch')))\n",
    "        \n",
    "        # Select year, month, and day from the drop-down menus\n",
    "        actions = ActionChains(browser)\n",
    "        year_select = Select(browser.find_element(By.ID,'yearSelection'))\n",
    "        year_select.select_by_value(str((2023-year))+':'+' '+str(year))\n",
    "        month_select = Select(browser.find_element(By.ID,'monthSelection'))\n",
    "        month_select.select_by_value(str(month))\n",
    "        day_select = Select(browser.find_element(By.ID,'daySelection'))\n",
    "        day_select.select_by_value(str((day-1))+':'+' '+str(day))\n",
    "     \n",
    "        search_field = wait.until(EC.visibility_of_element_located((By.ID, 'historySearch')))\n",
    "        search_field.click()\n",
    "        search_field.send_keys(\"New York, NY\", Keys.ENTER)\n",
    "        #search_field.send_keys(Keys.TAB * 2 )#+ Keys.RETURN * 2)\n",
    "     \n",
    "\n",
    "        try:\n",
    "            wait.until(EC.element_to_be_clickable((By.ID, 'dateSubmit')))\n",
    "            button_view = browser.find_element(By.ID, 'dateSubmit')\n",
    "            #button_view.send_keys(\"\",Keys.ENTER)\n",
    "            actions.move_to_element(button_view).double_click(button_view)\n",
    "        except TimeoutError as te:\n",
    "            print(f\"The following element caused a timeout error: {te}\")\n",
    "       \n",
    "    # Click the \"View\" button to load the data for the selected date\n",
    "        #button_view = wait.until(EC.element_to_be_clickable((By.ID, 'dateSubmit')))\n",
    "        #actions.move_to_element(button_view).click().perform()\n",
    "        #button_view.click()\n",
    "        #browser.find_element(By.ID, 'dateSubmit').click\n",
    "        #WebDriverWait(browser, 2)\n",
    "        #browser.find_element(By.ID, 'dateSubmit').click\n",
    "        \n",
    "        # Wait for the data to load\n",
    "        wait.until_not(EC.presence_of_element_located((By.XPATH, '//div[@class=\"loading-indicator\"]')))\n",
    "        wait.until(EC.visibility_of_element_located((By.CLASS_NAME, 'row')))\n",
    "        wait.until(EC.presence_of_element_located((By.XPATH, '//table[@class=\"mat-table cdk-table mat-sort ng-star-inserted\"]')))\n",
    "    \n",
    "    except TimeoutError:\n",
    "        raise Exception(\"Timeout Error: Could not load data from URL\")\n",
    "    \n",
    "    # Extract the data from the table using BeautifulSoup\n",
    "    soup = BeautifulSoup(browser.page_source, 'html.parser')\n",
    "    table = soup.select_one('table[class*=\"mat-table cdk-table mat-sort ng-star-inserted\"]')\n",
    "    rows = table.find_all('tr',{'class':'mat-row cdk-row ng-star-inserted'})\n",
    "  \n",
    "    time = []\n",
    "    temperature = []\n",
    "    dew_point = []\n",
    "    humidity = []\n",
    "    precipitation = []\n",
    "    wind_speed = []\n",
    "    wind_dir = []\n",
    "    condition = []\n",
    "    \n",
    "    for row in rows[1:len(rows)-1]:\n",
    "        cells = row.find_all('td')\n",
    "       \n",
    "        time.append(cells[0].text)\n",
    "        \n",
    "        temperature_element = cells[1].find('span', class_='wu-value wu-value-to')\n",
    "        temperature.append(temperature_element.text)\n",
    "        \n",
    "        dew_point_element = cells[2].find('span', class_='wu-value wu-value-to')\n",
    "        dew_point.append(dew_point_element.text)\n",
    "        \n",
    "        humidity_element = cells[3].find('span', class_='wu-value wu-value-to')\n",
    "        humidity.append(humidity_element.text)\n",
    "        \n",
    "        wind_dir_element = cells[4].find('span', class_='ng-star-inserted')\n",
    "        wind_dir.append(wind_dir_element.text)\n",
    "        \n",
    "        wind_speed_element = cells[5].find('span', class_='wu-value wu-value-to')\n",
    "        wind_speed.append(wind_speed_element.text)\n",
    "        \n",
    "        precipitation_element = cells[8].find('span', class_='wu-value wu-value-to')\n",
    "        precipitation.append(precipitation_element.text)\n",
    "       \n",
    "        condition_element = cells[9].find('span', class_='ng-star-inserted')\n",
    "        condition.append(condition_element.text)\n",
    "        \n",
    "    #calculating avg\n",
    "    temperature_avg = fahrenheit_to_celsius(sum(float(t) for t in temperature) / len(temperature))\n",
    "    precipitation_avg = sum(float(p) for p in precipitation) / len(precipitation)\n",
    "    wind_avg = mph_to_kmh(sum(float(w) for w in wind_speed) / len(wind_speed))\n",
    "    humidity_avg = sum(float(r) for r in humidity) / len(humidity)\n",
    "    dew_point_avg = fahrenheit_to_celsius(sum(float(r) for r in dew_point) / len(dew_point))\n",
    "    wind_dir_mf = most_frequent_wind_direction(wind_dir)    \n",
    "    condition_mf = most_frequent_string(condition)\n",
    "    \n",
    "   # Close the browser\n",
    "    #browser.quit()\n",
    "    data = {'Year': year, 'Month': month, 'Day': day, \n",
    "            'Temperature': temperature_avg, \n",
    "            'Temp Dew Point': dew_point_avg,\n",
    "            'Humidity': humidity_avg,\n",
    "            'Wind Direction': wind_dir_mf, \n",
    "            'Wind Speed': wind_avg, \n",
    "            'Precipitation': precipitation_avg,\n",
    "            'Condition': condition_mf}\n",
    "    return data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "b9a72974",
   "metadata": {},
   "outputs": [],
   "source": [
    "def most_frequent_wind_direction(arr):\n",
    "    wind_directions = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE',\n",
    "                       'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW',\n",
    "                       'W', 'WNW', 'NW', 'NNW', 'CALM','VAR']\n",
    "    \n",
    "    valid_directions = []\n",
    "    for direction in arr:\n",
    "        if direction in wind_directions:\n",
    "            valid_directions.append(direction)\n",
    "        else:\n",
    "            print(f\"Warning: Invalid wind direction '{direction}' found in the input array\")\n",
    "    \n",
    "    count = Counter(valid_directions)\n",
    "    return count.most_common(1)[0][0]\n",
    "\n",
    "def most_frequent_string(strings):\n",
    "    frequency = {}\n",
    "    max_frequency = 0\n",
    "    most_frequent_string = None\n",
    "    for string in strings:\n",
    "        if string in frequency:\n",
    "            frequency[string] += 1\n",
    "        else:\n",
    "            frequency[string] = 1\n",
    "        if frequency[string] > max_frequency:\n",
    "            max_frequency = frequency[string]\n",
    "            most_frequent_string = string\n",
    "    return most_frequent_string\n",
    " \n",
    "    # Conversions\n",
    "def fahrenheit_to_celsius(temp_fahrenheit):\n",
    "    temp_celsius = (temp_fahrenheit - 32) * 5/9\n",
    "    return temp_celsius\n",
    "\n",
    "def mph_to_kmh(mph):\n",
    "    kmh = mph * 1.609344\n",
    "    return kmh"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "10644525",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:An error occurred while getting data for date 2010-09-20 00:00:00: Message: \n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16\n",
      "\n",
      "ERROR:root:Maximum number of retries reached for date 2010-09-20 00:00:00\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459CEA7C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9f05f61d-4654-41ad-85a4-53ed46ad0799/window\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D4599504F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9f05f61d-4654-41ad-85a4-53ed46ad0799/window\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459CEA940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9f05f61d-4654-41ad-85a4-53ed46ad0799/window\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459CE5850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9f05f61d-4654-41ad-85a4-53ed46ad0799\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459CE5910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9f05f61d-4654-41ad-85a4-53ed46ad0799\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459CE5F40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9f05f61d-4654-41ad-85a4-53ed46ad0799\n",
      "ERROR:root:An error occurred while getting data for date 2010-09-21 00:00:00: Message: \n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16\n",
      "\n",
      "ERROR:root:Maximum number of retries reached for date 2010-09-21 00:00:00\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459D19D00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/32cfea83-2392-450b-8bcc-b3bdae904ad8/window\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459D19CA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/32cfea83-2392-450b-8bcc-b3bdae904ad8/window\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459D19CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/32cfea83-2392-450b-8bcc-b3bdae904ad8/window\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459D06BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/32cfea83-2392-450b-8bcc-b3bdae904ad8\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459CE51C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/32cfea83-2392-450b-8bcc-b3bdae904ad8\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459CE5EB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/32cfea83-2392-450b-8bcc-b3bdae904ad8\n",
      "ERROR:root:An error occurred while getting data for date 2010-09-22 00:00:00: Message: \n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16\n",
      "\n",
      "ERROR:root:Maximum number of retries reached for date 2010-09-22 00:00:00\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459D07A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c3b674d8-788c-488e-a32b-0502fde6a95e/window\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459977310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c3b674d8-788c-488e-a32b-0502fde6a95e/window\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459D076D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c3b674d8-788c-488e-a32b-0502fde6a95e/window\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459D07460>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c3b674d8-788c-488e-a32b-0502fde6a95e\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459D079A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c3b674d8-788c-488e-a32b-0502fde6a95e\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459D07130>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c3b674d8-788c-488e-a32b-0502fde6a95e\n",
      "ERROR:root:An error occurred while getting data for date 2010-09-23 00:00:00: Message: \n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16\n",
      "\n",
      "ERROR:root:Maximum number of retries reached for date 2010-09-23 00:00:00\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459D19520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/10909e32-d7cf-4e39-80f1-acbc959d51b9\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459950970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/10909e32-d7cf-4e39-80f1-acbc959d51b9\n",
      "WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D459D1CF70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/10909e32-d7cf-4e39-80f1-acbc959d51b9\n"
     ]
    },
    {
     "ename": "KeyError",
     "evalue": "\"Only a column name can be used for the key in a dtype mappings argument. 'Year' not found in columns.\"",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_5712\\3634549942.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[0mweather_data\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mproblematic_urls\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mget_weather_data_for_dates7\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m2010\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m9\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m20\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m2010\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m9\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m23\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbrowser\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;31m#17/09/2010 - problematic\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[0mweather_data_df\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mDataFrame\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfrom_dict\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mweather_data\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtranspose\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 7\u001b[1;33m \u001b[0mweather_data_df\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mweather_data_df\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mastype\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;34m'Year'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mint\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'Month'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mint\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'Day'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mint\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      8\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      9\u001b[0m \u001b[1;31m#saving collected data:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\pandas\\core\\generic.py\u001b[0m in \u001b[0;36mastype\u001b[1;34m(self, dtype, copy, errors)\u001b[0m\n\u001b[0;32m   5877\u001b[0m             \u001b[1;32mfor\u001b[0m \u001b[0mcol_name\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mdtype\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mkeys\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   5878\u001b[0m                 \u001b[1;32mif\u001b[0m \u001b[0mcol_name\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 5879\u001b[1;33m                     raise KeyError(\n\u001b[0m\u001b[0;32m   5880\u001b[0m                         \u001b[1;34m\"Only a column name can be used for the \"\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   5881\u001b[0m                         \u001b[1;34m\"key in a dtype mappings argument. \"\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mKeyError\u001b[0m: \"Only a column name can be used for the key in a dtype mappings argument. 'Year' not found in columns.\""
     ]
    }
   ],
   "source": [
    "#MAIN\n",
    "browser = webdriver.Firefox()\n",
    "browser.maximize_window()\n",
    "#weather_data, problematic_urls = get_weather_data_for_dates7(2010, 8, 4, 2023, 1, 15, browser)\n",
    "weather_data, problematic_urls = get_weather_data_for_dates7(2010, 9, 20, 2010, 9, 23, browser) #17/09/2010 - problematic\n",
    "weather_data_df = pd.DataFrame.from_dict(weather_data).transpose()\n",
    "weather_data_df = weather_data_df.astype({'Year': int, 'Month': int, 'Day': int})\n",
    "\n",
    "#saving collected data:\n",
    "weather_data_df.to_csv(\"weather_data.csv\", index=False)\n",
    "weather_data_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0f4e8347",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a DataFrame from the problematic_urls list\n",
    "problematic_urls_df = pd.DataFrame(problematic_urls, columns=['Date', 'URL'])\n",
    "\n",
    "# Save the DataFrame to a CSV file\n",
    "problematic_urls_df.to_csv('problematic_urls_for_weather_data.csv', index=False)\n",
    "problematic_urls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8616ca49",
   "metadata": {},
   "outputs": [],
   "source": [
    "   #search_field.click()\n",
    "        \n",
    "        #search_field.send_keys(\"New York, NY\")\n",
    "        #search_field.submit()\n",
    "       \n",
    "        # Wait for the auto-complete menu to become visible\n",
    "        #wait.until(EC.visibility_of_element_located((By.CLASS_NAME, \"ui-autocomplete ui-front ui-menu ui-widget ui-widget-content ui-corner-all\")))\n",
    "        #wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, \".ui-autocomplete.ui-front.ui-menu.ui-widget.ui-widget-content.ui-corner-all\")))\n",
    "        #autocomplete_element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, \".ui-autocomplete\")))\n",
    "        #element = driver.find_elements_by_css_selector('li.needsclick.needsfocus.defcon-.is-city:nth-of-type(2) a span.needsclick.needsfocus.city-name span.ui-autocomplete-term')[0]\n",
    "        #element.click()\n",
    "        #try:\n",
    "            #wait.until(EC.element_to_be_clickable.find_element(By.XPATH, \"//span[@class='needsclick needsfocus city-name ng-star-inserted']/span[@class='ui-autocomplete-term'][text()='New York']/following-sibling::text()[1][normalize-space(.)=', NY']\").click()\n",
    "        #except NoSuchElementException:\n",
    "            #print(\"No such element was found\")\n",
    "\n",
    "        # Find the auto-complete list\n",
    "        #autocomplete_list = browser.find_element(By.CSS_SELECTOR, \"ul.ui-autocomplete\")\n",
    "\n",
    "        # Find the first option that is not \"airports\"\n",
    "        #first_option = autocomplete_list.find_elements(By.CSS_SELECTOR, \"li:not(.result-type-airports)\")[0]\n",
    "\n",
    "        # Find the first <li> element with <a> inside it\n",
    "       # first_result = browser.find_element_by_css_selector(\"ul.ui-autocomplete li:not(.result-type-airports) a\")\n",
    "        # Click the first result\n",
    "        #first_result.click()\n",
    "        #first_option.click()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
